export const gardenQuotes = [
  // Timeless / Reflective
  "To plant a garden is to believe in tomorrow. — Audrey Hepburn",
  "A garden is a grand teacher. — Gertrude Jekyll",
  "He who plants a garden plants happiness. — Chinese Proverb",
  "Gardens are not made by singing 'Oh, how beautiful,' and sitting in the shade. — Rudyard Kipling",
  "The glory of gardening: hands in the dirt, head in the sun, heart with nature. — Alfred Austin",
  "If you have a garden and a library, you have everything you need. — Cicero",
  "A garden requires patient labor and attention. Plants do not grow merely to satisfy ambitions or to fulfill good intentions. They thrive because someone expended effort on them. — Liberty Hyde Bailey",
  "The garden suggests there might be a place where we can meet nature halfway. — Michael Pollan",
  "God Almighty first planted a garden. And indeed, it is the purest of human pleasures. — Francis Bacon",
  "There are no gardening mistakes, only experiments. — Janet Kilburn Phillips",
  "A garden is a friend you can visit any time. — Unknown",
  "Gardening is the art that uses flowers and plants as paint, and the soil and sky as canvas. — Elizabeth Murray",
  "The kiss of the sun for pardon, the song of the birds for mirth, one is nearer God's heart in a garden than anywhere else on earth. — Dorothy Frances Gurney",
  "Half the interest of a garden is the constant exercise of the imagination. — Alice Morse Earle",

  // Poetic / Whimsical
  "In every walk with nature one receives far more than he seeks. — John Muir",
  "Where flowers bloom, so does hope. — Lady Bird Johnson",
  "A flower does not think of competing with the flower next to it. It just blooms. — Zen Shin",
  "The earth laughs in flowers. — Ralph Waldo Emerson",
  "I must have flowers, always, and always. — Claude Monet",
  "My garden is my most beautiful masterpiece. — Claude Monet",
  "Weeds are flowers too, once you get to know them. — A.A. Milne",
  "In the spring, at the end of the day, you should smell like dirt. — Margaret Atwood",
  "A morning glory at my window satisfies me more than the metaphysics of books. — Walt Whitman",
  "How fair is a garden amid the trials and passions of existence. — Benjamin Disraeli",
  "Life begins the day you start a garden. — Chinese Proverb",
  "Everything that slows us down and forces patience, everything that sets us back into the slow circles of nature, is a help. — May Sarton",
  "The butterfly counts not months but moments, and has time enough. — Rabindranath Tagore",
  "I perhaps owe having become a painter to flowers. — Claude Monet",
  "Perfumes are the feelings of flowers. — Heinrich Heine",
  "In joy or sadness, flowers are our constant friends. — Okakura Kakuzo",
  "Every flower is a soul blossoming in nature. — Gérard de Nerval",
  "Some old-fashioned things like fresh air and sunshine are hard to beat. — Laura Ingalls Wilder",
  "Let us dance in the sun, wearing wild flowers in our hair. — Susan Polis Schutz",
  "The hum of bees is the voice of the garden. — Elizabeth Lawrence",
  "Sunshine is delicious, rain is refreshing, wind braces us up, snow is exhilarating; there is really no such thing as bad weather, only different kinds of good weather. — John Ruskin",
  "What a desolate place would be a world without a flower. — A.J. Balfour",

  // Funny / Light
  "Gardening is cheaper than therapy, and you get tomatoes. — Unknown",
  "I'm sorry for what I said before I had my morning garden time. — Unknown",
  "Plant dreams, pull weeds, grow a happy life. — Unknown",
  "Gardening adds years to your life, and life to your years. — Unknown",
  "I garden so I'm not in jail. It's a choice. — Unknown",
  "My therapist told me to talk to my plants. Now my fern knows everything. — Unknown",
  "Gardening: where killing things is just called 'learning experience.' — Unknown",
  "I like gardening — it's a place where I find myself when I need to lose myself. — Alice Sebold",
  "I don't always test my code, but when I do, I do it in production. Same with gardening. — Unknown",
  "I know a lot of plants. Not all of them are still alive, but I know them. — Unknown",
  "My houseplants are proof that I am an optimist. — Unknown",
  "Gardening is just really slow cooking. — Unknown",
  "I have a lot of growing up to do. I realized that the other day inside my fort. — Zach Galifianakis",
  "I don't have a green thumb. I have a thumb of death. But I keep trying. — Unknown",
  "A weed is just a plant in the wrong place. — Unknown",
  "Behind every successful garden is a person who really wanted to sit down but went outside anyway. — Unknown",
  "My favorite exercise is a cross between a lunge and a crunch. I call it lunch. But gardening is a close second. — Unknown",

  // Growth / Wisdom
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson",
  "A society grows great when old men plant trees in whose shade they shall never sit. — Greek Proverb",
  "Though I do not believe that a plant will spring up where no seed has been, I have great faith in a seed. — Henry David Thoreau",
  "What is a weed? A plant whose virtues have not yet been discovered. — Ralph Waldo Emerson",
  "To forget how to dig the earth and to tend the soil is to forget ourselves. — Mahatma Gandhi",
  "Adopt the pace of nature: her secret is patience. — Ralph Waldo Emerson",
  "We can complain because rose bushes have thorns, or rejoice because thorns have roses. — Alphonse Karr",
  "All gardening is landscape painting. — William Kent",
  "One of the most delightful things about a garden is the anticipation it provides. — W.E. Johns",
  "The love of gardening is a seed once sown that never dies. — Gertrude Jekyll",
  "Flowers always make people better, happier, and more helpful. — Luther Burbank",
  "Trees and plants always look like the people they live with, somehow. — Zora Neale Hurston",
  "Show me your garden and I shall tell you what you are. — Alfred Austin",
  "Use plants to bring life. — Douglas Wilson",
  "To see things in the seed, that is genius. — Lao Tzu",
  "When the flower blooms, the bees come uninvited. — Ramakrishna",
  "Bloom where you are planted. — Bishop of Geneva",
  "A tree is known by its fruit. — Matthew 12:33",
  "The creation of a thousand forests is in one acorn. — Ralph Waldo Emerson",
  "Keep your face to the sunshine and you cannot see the shadows. — Helen Keller",
  "Water is the driving force of all nature. — Leonardo da Vinci",
  "Every gardener knows that under the cloak of winter lies a miracle. — Luther Burbank",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",

  // Nature / Seasons
  "No winter lasts forever; no spring skips its turn. — Hal Borland",
  "Spring is nature's way of saying 'Let's party!' — Robin Williams",
  "Autumn is a second spring when every leaf is a flower. — Albert Camus",
  "Live in the sunshine, swim in the sea, drink the wild air. — Ralph Waldo Emerson",
  "If we could see the miracle of a single flower clearly, our whole life would change. — Buddha",
  "The clearest way into the universe is through a forest wilderness. — John Muir",
  "Look deep into nature, and then you will understand everything better. — Albert Einstein",
  "Study nature, love nature, stay close to nature. It will never fail you. — Frank Lloyd Wright",
  "In all things of nature there is something of the marvelous. — Aristotle",
  "The best fertilizer is the gardener's shadow. — Chinese Proverb",
  "It is only the farmer who faithfully plants seeds in the spring, who reaps a harvest in the autumn. — B.C. Forbes",
  "By plucking her petals, you do not gather the beauty of the flower. — Rabindranath Tagore",

  // Mindfulness / Joy
  "I go to nature to be soothed and healed, and to have my senses put in order. — John Burroughs",
  "Sit quietly, doing nothing, spring comes, and the grass grows by itself. — Matsuo Basho",
  "Planting is one of my great amusements. — Thomas Jefferson",
  "The garden is a love song, a duet between a human being and Mother Nature. — Jeff Cox",
  "All my hurts my garden spade can heal. — Ralph Waldo Emerson",
  "I grow plants for many reasons: to please my eye or to please my soul, to challenge the elements or to challenge my patience. — Joy Larkcom",
  "In search of my mother's garden, I found my own. — Alice Walker",
  "A garden to walk in and immensity to dream in — what more could he ask? — Victor Hugo",
  "The soul cannot thrive in the absence of a garden. — Thomas More",
  "There is no gardening without humility. — Alfred Austin",
];
